# Generated by Django 5.0.3 on 2024-03-12 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data_url', models.TextField()),
                ('cell_id', models.CharField(blank=True, max_length=10)),
                ('cell_condition', models.CharField(choices=[('New', 'New'), ('Recycled', 'Recycled')], default='Recycled', max_length=8)),
                ('manufacturer', models.CharField(default='Molicel', max_length=20)),
                ('model', models.CharField(default='INR21700-P45B', max_length=30)),
                ('type', models.CharField(default='Li-ion', max_length=20)),
                ('form_factor', models.CharField(default='Cylindrical 21700', max_length=20)),
                ('mass', models.DecimalField(decimal_places=2, default=70, max_digits=10)),
                ('mass_unit', models.CharField(choices=[('g', 'Grams')], max_length=1)),
                ('height', models.DecimalField(decimal_places=2, default=70.15, max_digits=10)),
                ('height_unit', models.CharField(choices=[('mm', 'Millimeters')], max_length=2)),
                ('diameter', models.DecimalField(decimal_places=2, default=21.55, max_digits=10)),
                ('diameter_unit', models.CharField(choices=[('mm', 'Millimeters')], max_length=2)),
                ('volume', models.CharField(choices=[('cm3', 'Cubic centimeter')], max_length=3)),
                ('nominal_voltage', models.DecimalField(decimal_places=2, default=3.6, max_digits=10)),
                ('nominal_voltage_unit', models.CharField(choices=[('V', 'V')], default='V', max_length=1)),
                ('nominal_energy', models.DecimalField(decimal_places=2, default=16.2, max_digits=10)),
                ('nominal_energy_unit', models.CharField(choices=[('Wh', 'Wh')], default='Wh', max_length=2)),
                ('nominal_charge_capacity', models.DecimalField(decimal_places=2, default=4.5, max_digits=10)),
                ('nominal_charge_capacity_unit', models.CharField(choices=[('Ah', 'Ah')], default='Ah', max_length=2)),
                ('voltage_range', models.CharField(default='2.5-4.2', max_length=10)),
                ('voltage_range_unit', models.CharField(choices=[('V', 'V')], default='V', max_length=1)),
                ('current_continuous', models.DecimalField(decimal_places=2, default=8.61, max_digits=10)),
                ('current_continuous_unit', models.CharField(choices=[('A', 'A')], default='A', max_length=1)),
                ('current_peak', models.DecimalField(decimal_places=2, default=17.5, max_digits=10)),
                ('current_peak_unit', models.CharField(choices=[('A', 'A')], default='A', max_length=1)),
                ('power_continuous', models.DecimalField(decimal_places=2, default=25.6, max_digits=10)),
                ('power_continuous_unit', models.CharField(choices=[('W', 'W')], default='W', max_length=1)),
                ('power_peak', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('power_peak_unit', models.CharField(choices=[('W', 'W')], default='W', max_length=1)),
                ('energy_density_gravimetric', models.DecimalField(decimal_places=2, default=154, max_digits=10)),
                ('energy_density_gravimetric_unit', models.CharField(choices=[('Wh/kg', 'Wh/kg')], default='Wh/kg', max_length=5)),
                ('energy_density_volumetric', models.DecimalField(decimal_places=2, default=375, max_digits=10)),
                ('energy_density_volumetric_unit', models.CharField(choices=[('Wh/l', 'Wh/l')], default='Wh/l', max_length=4)),
                ('power_density_gravimetric', models.DecimalField(decimal_places=2, default=837, max_digits=10)),
                ('power_density_gravimetric_unit', models.CharField(choices=[('W/kg', 'W/kg')], default='W/kg', max_length=4)),
                ('power_density_volumetric', models.DecimalField(decimal_places=2, default=2.04, max_digits=10)),
                ('power_density_volumetric_unit', models.CharField(choices=[('kW/l', 'kW/l')], default='kW/l', max_length=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
