# Generated by Django 5.0.3 on 2024-03-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='diameter_unit',
            field=models.CharField(choices=[('mm', 'Millimeters')], default='mm', max_length=2),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='height_unit',
            field=models.CharField(choices=[('mm', 'Millimeters')], default='mm', max_length=2),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='mass_unit',
            field=models.CharField(choices=[('g', 'Grams')], default='g', max_length=1),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='volume',
            field=models.CharField(choices=[('cm3', 'Cubic centimeter')], default='mm', max_length=3),
        ),
    ]
