# Generated by Django 5.0.3 on 2024-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_batterycell_diameter_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterycell',
            name='volume_unit',
            field=models.CharField(choices=[('cm3', 'Cubic centimeter')], default='mm', max_length=3),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=25.59, max_digits=10),
        ),
    ]
